# ========== interfaces ==========
interface=br0
bind-dynamic

# ========== DHCPv4 ==========
dhcp-range=192.168.1.100,192.168.1.255,12h

# ========== DNS ==========
server=/elk-agama.ts.net/100.100.100.100
dhcp-option=119,home.arpa,elk-agama.ts.net
domain=home.arpa
local=/home.arpa/

# ========== IPv6 RA ==========
enable-ra
# ra-stateless: SLAAC
dhcp-range=::,constructor:br0,ra-stateless
